{
 "title": "MMX Node Dashboard",
 "tags": [ "mmx" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Farm", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Sync Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mmx_node_synced" }
   ]
  },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mmx_block_height" }
   ]
  },
  {
   "title": "Farm Blocks Summary",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 1 },
   "targets": [
    { "expr": "mmx_farm_blocks_count", "legendFormat": "Block Count" },
    { "expr": "mmx_farm_blocks_total_rewards", "legendFormat": "Total Rewards" }
   ]
  },
  {
   "title": "Farmed Blocks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mmx_farm_blocks_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Plot Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "mmx_plot_count", "legendFormat": "plots" }
   ]
  },
  {
   "title": "Farm Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mmx_farm_size_tb * 1024^4", "legendFormat": "Total Size" },
    {
     "expr": "mmx_farm_size_effective_tb * 1024^4",
     "legendFormat": "Effective Size"
    }
   ]
  },
  {
   "title": "Total Balance",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mmx_wallet_balance{type=\"total\"}"
    }
   ]
  },
  {
   "title": "Spendable Balance",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mmx_wallet_balance{type=\"spendable\"}"
    }
   ]
  },
  {
   "title": "Wallet Balance History",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mmx_wallet_balance{type=\"total\"}",
     "legendFormat": "{{account}} Total"
    },
    {
     "expr": "mmx_wallet_balance{type=\"spendable\"}",
     "legendFormat": "{{account}} Spendable"
    },
    {
     "expr": "mmx_wallet_balance{type=\"locked\"}",
     "legendFormat": "{{account}} Locked"
    },
    {
     "expr": "mmx_wallet_balance{type=\"reserved\"}",
     "legendFormat": "{{account}} Reserved"
    }
   ]
  },
  {
   "title": "Block Height vs VDF Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "mmx_block_height", "legendFormat": "Block Height" },
    { "expr": "mmx_vdf_height", "legendFormat": "VDF Height" },
    {
     "expr": "mmx_block_height/mmx_vdf_height",
     "legendFormat": "Delta"
    }
   ]
  },
  {
   "title": "Time To Win",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(10 / ((mmx_farm_size_tb * 1024) / mmx_total_space)) / 3600",
     "legendFormat": "TTW"
    }
   ]
  },
  {
   "title": "Time To Win",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "expr": "(10 / ((mmx_farm_size_tb * 1024) / mmx_total_space)) / 3600",
     "legendFormat": "TTW"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Netspace",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    { "expr": "mmx_total_space", "legendFormat": "Total Size" },
    {
     "expr": "avg_over_time(mmx_total_space[1d])",
     "legendFormat": "1 day"
    },
    {
     "expr": "avg_over_time(mmx_total_space[7d])",
     "legendFormat": "7 days"
    }
   ]
  },
  {
   "title": "Average TX Fee",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "mmx_average_txfee", "legendFormat": "tx fees" },
    {
     "expr": "avg_over_time(mmx_average_txfee[1d])",
     "legendFormat": "tx fees"
    }
   ]
  },
  {
   "title": "Block Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "mmx_block_size", "legendFormat": "Block Size" },
    {
     "expr": "avg_over_time(mmx_block_size[1d])",
     "legendFormat": "1d"
    }
   ]
  },
  {
   "title": "VDF Height",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mmx_vdf_height" }
   ]
  },
  {
   "title": "VDF Speed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mmx_vdf_speed" }
   ]
  }
 ]
}